version: 2

jobs:

  build:
    working_directory: "~/projects/fs2-kafka-client"

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - checkout

    - restore_cache:
        keys:
          - "dependencies-{{ .Branch }}"

    - run:
        command: sbt update
        no_output_timeout: 20m

    - save_cache:
        key: "dependencies-{{ .Branch }}"
        paths:
          - /home/circleci/.ivy2
          - /home/circleci/.sbt
          - /home/circleci/.coursier
          - project/target/resolution-cache
          - target/resolution-cache

    - run:
        command: sbt test:compile
        no_output_timeout: 20m

    - persist_to_workspace:
        root: ~/projects
        paths:
          - "fs2-kafka-client"

  test:
    working_directory: "~/projects/fs2-kafka-client"

    docker:
    - image: circleci/openjdk:8-jdk

    steps:

    - attach_workspace:
        at: ~/projects

    - restore_cache:
        keys:
          - "dependencies-{{ .Branch }}"

    - run:
        command: "sbt test"
        no_output_timeout: 20m

    - store_artifacts:
        path: target/test-reports

  tag:
    working_directory: "~/projects/fs2-kafka-client"

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - attach_workspace:
        at: ~/projects

    - restore_cache:
        keys:
          - "dependencies-{{ .Branch }}"

    - run:
        name: Configure git credentials
        command: |
          echo 'Adding the github host SSH key...'
          mkdir -p -m 0700 ~/.ssh/
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config user.name ovo-comms-circleci
          git config user.email "hello.comms@ovoenergy.com"

    - run:
        command: "build/tag.sh"

    # Update the workspace to make sure the git tags are available to the
    # downstream jobs
    - persist_to_workspace:
        root: ~/projects
        paths:
          - "audit"

  publish:
    working_directory: "~/projects/fs2-kafka-client"

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - attach_workspace:
        at: ~/projects

    - restore_cache:
        keys:
          - "dependencies-{{ .Branch }}"

    - run:
        command: "sbt publish"
        no_output_timeout: 20m

workflows:
  version: 2

  build-test-tag-publish:
    jobs:
    - build

    - test:
        requires:
        - build

    - tag:
        requires:
        - test
        filters:
          branches:
            only: master

    - publish:
        requires:
        - tag
